// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(p,j,i){var n=jQuery,l=n(this),o=n(".ws_list",i),k={position:"absolute",left:0,top:0,width:"100%",height:"100%",maxHeight:"none",maxWidth:"none",transform:"translate3d(0,0,0)"},m=n("<div>").addClass("ws_effect ws_fade").css(k).css("overflow","hidden").appendTo(i);this.go=function(e,d){var c=n(j.get(e)),a={width:c.width(),height:c.height()};c=c.clone().css(k).css(a).appendTo(m);if(!p.noCross){var b=n(j.get(d)).clone().css(k).css(a).appendTo(m);wowAnimate(b,{opacity:1},{opacity:0},p.duration,function(){b.remove()})}wowAnimate(c,{opacity:0},{opacity:1},p.duration,function(){l.trigger("effectEnd");c.remove()})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:20*100,delay:20*100,width:750,height:400,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:true,captionEffect:"none",controls:true,responsive:1,fullScreen:false,gestures:2,onBeforeStep:0,images:0});

jQuery("#wowslider-container2").wowSlider({effect:"slide",duration:20*100,delay:3000,controls:false});